baseURL = "https://musale.github.io"
footnoteReturnLinkContents = "↩"
title = "musale"

[params]
  AuthorName = "Martin Musale"
  GitHubUser = "musale"
  Subtitle = "Musale is Absurdly Fast!"

[permalinks]
  posts = "/:year/:month/:title/"
